export const types = {
  SET_PAGE: 'USERS/SET_PAGE',
  SET_PAGE_SIZE: 'USERS/SET_PAGE_SIZE',
  SET_DATA: 'USERS/SET_DATA',
  TOGGLE_ROW_SELECTION: 'USERS/TOGGLE_ROW_SELECTION',
  TOGGLE_ALL_SELECTION: 'USERS/TOGGLE_ALL_SELECTION',
};
